media: src/media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    fields: 
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: string }
      - { name: tags, label: Tags, type: string }
      - { name: images, label: Images, type: image, list: true}
      - { name: body, label: Body, type: rich-text}
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
